import Head from 'next/head'
import Feeds from '../components/Feeds'
import Header from '../components/Header'
import Nav from '../components/Nav'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='theme-color' content="#06202A"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Feeds */}
      <Feeds />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
}
