import Head from 'next/head'
import Feeds from '../components/Feeds'
import Header from '../components/Header'
import Nav from '../components/Nav'
import requests from '../utils/requests'

export default function Home(props) {
  console.log(props);
  return (
    <div >
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='theme-color' content="#06202A"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Feeds */}
      <Feeds />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());
  // const allResults = JSON.stringify(results)
  return {
    props: {
      results: request.results,
    }
  }
}
